services:
  - type: web
    name: django-chat-app
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "./run.sh"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: django-chat-db
          property: connectionString

databases:
  - name: django-chat-db
    plan: free
